services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      TZ: Asia/Seoul
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      TZ: Asia/Seoul
    depends_on:
      - postgres
volumes:
  postgres-data: