spring:
  application:
    name: "sample-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/dongajul_user
    username: dongajul_user
    password: dongajul
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/