spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
        order_updates: true
        connection:
          pool_size: 10
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: never
      data-locations:
        - classpath:data/ddl.sql
        - classpath:data/dml.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/dongajul_mentoring
    username: dongajul_mentoring
    password: dongajul
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
